"""
Swarm Plugin for David AI.
Orchestrates multi-agent workflows (Research & Write).
"""
import os
import json
import concurrent.futures
from typing import Dict, Any, List
from core.logger import get_logger
from ai.llm import generate_response
from tools.web_search import search_duckduckgo_summary
from plugins.base import BasePlugin

logger = get_logger(__name__)

class ResearcherAgent:
    def __init__(self, model_name: str="llama3.2"):
        self.model = model_name
        self.name = "Research Agent"

    def run(self, query: str) -> str:
        logger.info(f"[{self.name}] Searching web for: {query}")
        search_summary = search_duckduckgo_summary(query, num_results=5)
        
        prompt = f"""You are the Researcher Agent.
Analyze the following search results about "{query}" and compile a detailed factual dossier.
Extract ALL key numbers, facts, and quotes. Ignore filler.

Search Results:
{search_summary}

Dossier:"""
        try:
            dossier = generate_response([{"role": "user", "content": prompt}], model=self.model)
            return dossier
        except Exception as e:
            return "Failed to compile research."


class WriterAgent:
    def __init__(self, model_name: str="llama3.2"):
        self.model = model_name
        self.name = "Writer Agent"
        
    def run(self, topic: str, dossier: str, format_type: str="blog post") -> str:
        logger.info(f"[{self.name}] Drafting {format_type} based on dossier...")
        
        prompt = f"""You are the Writer Agent.
Write a highly engaging, professional {format_type} about "{topic}".
Base your writing EXCLUSIVELY on the provided research dossier.
Use markdown formatting (headers, bullet points, bold text).

Research Dossier:
{dossier}

Output {format_type}:"""
        
        try:
            draft = generate_response([{"role": "user", "content": prompt}], model=self.model)
            return draft
        except Exception as e:
            return "Failed to write draft."


class SwarmPlugin(BasePlugin):
    """
    Plugin to trigger the Multi-Agent Swarm Orchestrator.
    Handles 'swarm', 'research and write' commands.
    """
    
    def __init__(self):
        super().__init__()
        self.researcher = ResearcherAgent()
        self.writer = WriterAgent()
        
    def get_intents(self) -> List[str]:
        return ["swarm"]
        
    def get_description(self) -> str:
        return "Orchestrates multi-agent swarm tasks."
        
    def get_prompt_examples(self) -> str:
        return """
SWARM MULTI-AGENT HANDLER:
If the user asks to "research and write", "have the swarm write", or do a complex multi-step generative task (e.g., "Research AI and write a blog post"):
Provide intent format exactly: `{"intent": "swarm", "instruction": "the full user request"}`
"""

    def execute(self, intent_data: Dict[str, Any]) -> str:
        if intent_data.get("intent") == "swarm":
            instruction = intent_data.get("instruction", "")
            if not instruction:
                return "Please provide a specific instruction for the swarm to execute."
                
            return self.run_swarm(instruction)
        return ""

    def run_swarm(self, instruction: str) -> str:
        logger.info(f"🚀 [Swarm] Prompting manager: {instruction}")
        
        # 1. Orchestrator extracts params
        extract_prompt = f"""Extract the core research topic and desired writing format from this request: "{instruction}"
Respond ONLY in JSON format: {{"topic": "exact search query", "format": "e.g., blog post, email, report"}}"""
        
        try:
            response = generate_response([{"role": "user", "content": extract_prompt}], model="llama3.2")
            import re
            match = re.search(r'\{.*\}', response, re.DOTALL)
            if match:
                params = json.loads(match.group(0))
            else:
                params = {"topic": instruction, "format": "report"}
        except Exception:
            params = {"topic": instruction, "format": "report"}
            
        topic = params.get("topic", instruction)
        format_type = params.get("format", "report")
        
        # 2. Delegate to Researcher
        dossier = self.researcher.run(topic)
        
        # 3. Delegate to Writer
        final_draft = self.writer.run(topic, dossier, format_type)
        
        # 4. Save Output
        import time
        from core.config import BASE_DIR
        filename = os.path.join(BASE_DIR, f"Swarm_Output_{int(time.time())}.md")
        try:
            with open(filename, "w", encoding="utf-8") as f:
                f.write(f"# Swarm Objective: {instruction}\n\n{final_draft}\n\n---\n*Generated by David Swarm*")
        except Exception as e:
            logger.error(f"Failed to save output: {e}")
            
        return f"Swarm complete! I researched {topic} and generated a {format_type}. I saved it as {os.path.basename(filename)}."
